<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\InternalUserManagerControllers\" />
    <Folder Include="Controllers\ExternalUserManagerControllers\" />
    <Folder Include="Models\ExternalUserManagerModels\" />
    <Folder Include="Models\InternalUserManagerModels\" />
    <Folder Include="Views\Account\" />
  </ItemGroup>

</Project>
